export TASK="{\"_id\":\"5559edd38968ec0736000003\",\"data\":{\"step_1\":{\"uri\":\"546456456456456\"}},\"recipe\":{\"nodes\":[{\"id\":\"step_1\",\"compId\":\"testcomponent\",\"function\":\"newContacts\"}]}}"
export STEP_ID="step_1"
export AMQP_URI="amqp://guest:guest@127.0.0.1:5672"
export LISTEN_MESSAGES_ON="javasailor:test_exec:step_1:messages"
export PUBLISH_MESSAGES_TO="javasailor_exchange"
export DATA_ROUTING_KEY="javasailor.test_exec.step_1.message"
export ERROR_ROUTING_KEY="javasailor.test_exec.step_1.error"
export SNAPSHOT_ROUTING_KEY="javasailor.test_exec.step_1.snapshot"
export REBOUND_ROUTING_KEY="javasailor.test_exec.step_1.rebound"
export SHAPSHOT_ROUTING_KEY="javasailor.test_exec.step_1.rebound"
export COMPONENT_PATH="../component1"
export ELASTICIO_API_URI="http://localhost:5000"
export ELASTICIO_NO_SELF_PASSTRHOUGH="false"
export ELASTICIO_STARTUP_REQUIRED="true"
export ELASTICIO_API_REQUEST_RETRY_ATTEMPTS="5"
export ELASTICIO_API_KEY="test_api_key"
export ELASTICIO_API_USERNAME="test_api_username"
export ELASTICIO_COMP_ID="testcomponent"
export ELASTICIO_CONTAINER_ID="testcomponent_container"
export ELASTICIO_EXEC_ID="testcomponent_exec"
export ELASTICIO_FLOW_ID="testcomponent_flow"
export ELASTICIO_FUNCTION="testcomponent_function"
export ELASTICIO_STEP_ID="testcomponent_step"
export ELASTICIO_USER_ID="testcomponent_user"
export ELASTICIO_WORKSPACE_ID="testcomponent_workspace"

# java -cp "./build/classes/java/main:./build/libs/*:../petstore_component_java/*" io.elastic.sailor.Sailor
java -cp ./build/classes/main:./lib/*:../component1/build/classes/main/:../component1/lib/* io.elastic.sailor.Sailor